package model

import (
	"github.com/naoina/genmai"
)

type User struct {
	Id   int64  `db:"pk" json:"id"`
	Name string `json:"name"`

	genmai.TimeStamp
}

func (m *User) BeforeInsert() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return m.TimeStamp.BeforeInsert()
}

func (m *User) AfterInsert() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *User) BeforeUpdate() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return m.TimeStamp.BeforeUpdate()
}

func (m *User) AfterUpdate() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *User) BeforeDelete() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *User) AfterDelete() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}
